language: d

d:
  - dmd
  - gdc
  - ldc
  - dmd-2.069.0

script:
  - dub build
  - dub test
  - (cd "examples/Connected Components" && dub build)
  - (cd "examples/Dijkstra" && dub build)
  - (cd "examples/Astar Cities" && dub build)
